# Autogenerated at 2017-04-13T12:15:04.804021 on version 0.0.1
import casingSimulations

# Set up the simulation
sim = casingSimulations.run.SimulationFDEM(
    cp='CasingParameters.json',
    meshGenerator='MeshParameters.json',
    srcType='VerticalElectricDipole',
    fields_filename='fields.npy'
)

# run the simulation
fields = sim.run()
